import {NgModule} from '@angular/core';
import {
    MatInputModule,
    MatButtonModule,
    MatFormFieldModule,
    MatCardModule,
    MatToolbarModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatPaginatorModule,
    MatDialogModule,
    MatListModule,
    MatDatepickerModule,
    MatDividerModule,
    MatProgressBarModule,
    MatNativeDateModule,
    MatSidenavModule,
    MatStepperModule,
    MatSelectModule,
    MatRadioModule,
    MatIconModule,
    MatTabsModule,
    MAT_DIALOG_DATA,
    MatGridListModule,
    MatTableModule,
    MatCheckboxModule,
  } from '@angular/material';


@NgModule({

  imports: [MatInputModule,
    MatButtonModule,
    MatFormFieldModule,
    MatCardModule,
    MatToolbarModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatPaginatorModule,
    MatDialogModule,
    MatListModule,
    MatDatepickerModule,
    MatDividerModule,
    MatProgressBarModule,
    MatNativeDateModule,
    MatSidenavModule,
    MatStepperModule,
    MatSelectModule,
    MatRadioModule,
    MatIconModule,
    MatTabsModule,
    MatGridListModule],
    exports: [
    MatInputModule,
    MatButtonModule,
    MatFormFieldModule,
    MatCardModule,
    MatToolbarModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatPaginatorModule,
    MatDialogModule,
    MatListModule,
    MatDatepickerModule,
    MatDividerModule,
    MatProgressBarModule,
    MatNativeDateModule,
    MatSidenavModule,
    MatStepperModule,
    MatSelectModule,
    MatRadioModule,
    MatIconModule,
    MatTabsModule,
    MatTableModule,
    MatCheckboxModule,
    MatGridListModule],

    providers: [ { provide: MAT_DIALOG_DATA, useValue: {}}]
})
export class AngularMaterialModule {

}
